# https://github.com/JohnnyMorganz/StyLua?tab=readme-ov-file#options

column_width = 80
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "ForceDouble"
call_parentheses = "Always"
collapse_simple_statement = "Never"
